[platformio]
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = m5stack-cores3
framework = arduino
lib_deps =
  m5stack/M5Unified@0.2.19
  m5stack/M5GFX@0.2.26
  crankyoldgit/IRremoteESP8266@2.9.0
  m5stack/M5Unit-NFC@0.1.0
  https://github.com/m5stack/StackChan-BSP.git#f7ed40e6f5d9a1d08440cb926f3a0865b81882f8
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
build_unflags =
  -std=gnu++11
monitor_speed = 921600
