#pragma once

#include <cstddef>

// TypeScriptの正本をViteで読み込み、CoreS3とホストが同じカタログを返せる形へ変換する。
// clang-format off
namespace stackchan {
struct GeneratedGeneratorDefinition {
  const char* id;
  int version;
  const char* category;
  const char* costClass;
  int passes;
  double relativeFill;
  bool stateful;
};

struct GeneratedParameterDefinition {
  const char* generatorId;
  const char* id;
  const char* kind;
  double minimum;
  double maximum;
  bool hasRange;
  bool modulatable;
  const char* options;
};

struct GeneratedTextureDefinition {
  const char* generatorId;
  const char* id;
};

inline constexpr char kGeneratorCatalogJson[] = R"SC_CATALOG([{"id":"grid","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"material":["geometric","lattice"],"environment":["architectural"],"affect":["structured"]},"parameters":[{"id":"cells","label":"Cells","kind":"int","min":2,"max":64,"default":8,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0,"max":1,"default":0.08,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"points","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"material":["stipple","dot"],"motion":["static"],"affect":["sparse","tactile"]},"parameters":[{"id":"density","label":"Density","kind":"number","min":1,"max":64,"default":12,"modulatable":true},{"id":"size","label":"Size","kind":"number","min":0.01,"max":1,"default":0.15,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.45,"stateful":false}},{"id":"branch","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"material":["organic","line"],"environment":["dendritic","botanical"],"affect":["growth","structured"]},"parameters":[{"id":"depth","label":"Depth","kind":"int","min":1,"max":6,"default":4,"modulatable":true},{"id":"angle","label":"Angle","kind":"number","min":0,"max":1.5,"default":0.6,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.001,"max":0.2,"default":0.02,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.7,"stateful":false}},{"id":"cells","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"material":["cellular","mosaic"],"environment":["crystalline"],"affect":["organic","tessellated"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":1,"max":32,"default":6,"modulatable":true},{"id":"edge","label":"Edge","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.75,"stateful":false}},{"id":"tiles","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"environment":["urban"],"material":["tile"],"affect":["nostalgic"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":40,"default":8,"modulatable":true},{"id":"gap","label":"Gap","kind":"number","min":0.01,"max":0.3,"default":0.06,"modulatable":true},{"id":"stagger","label":"Stagger","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"wires","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"environment":["urban","suburban"],"motion":["static"],"affect":["nostalgic"]},"parameters":[{"id":"count","label":"Count","kind":"int","min":1,"max":8,"default":4,"modulatable":true},{"id":"sag","label":"Sag","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.002,"max":0.05,"default":0.008,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"concentric","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"material":["geometric","ring"],"motion":["static"],"affect":["hypnotic"]},"parameters":[{"id":"count","label":"Count","kind":"number","min":2,"max":40,"default":12,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.005,"max":0.2,"default":0.03,"modulatable":true},{"id":"wobble","label":"Wobble","kind":"number","min":0,"max":1,"default":0.25,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.45,"stateful":false}},{"id":"grille","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["sinosphere","taiwan-streetscape"],"material":["iron"],"affect":["nostalgic"]},"parameters":[{"id":"folds","label":"Folds","kind":"int","min":2,"max":12,"default":6,"modulatable":true},{"id":"density","label":"Density","kind":"int","min":1,"max":8,"default":3,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.004,"max":0.06,"default":0.012,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.65,"stateful":false}},{"id":"stripes","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"material":["stripe","graphic"],"motion":["static"],"affect":["graphic"]},"parameters":[{"id":"count","label":"Count","kind":"number","min":2,"max":64,"default":12,"modulatable":true},{"id":"duty","label":"Duty","kind":"number","min":0.05,"max":0.95,"default":0.45,"modulatable":true},{"id":"angle","label":"Angle","kind":"number","min":0,"max":180,"default":30,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"qilouShutter","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["taiwan-streetscape"],"environment":["urban"],"affect":["nostalgic","restrained"]},"parameters":[{"id":"density","label":"Density","kind":"number","min":8,"max":64,"default":32,"modulatable":true},{"id":"openness","label":"Openness","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true},{"id":"wear","label":"Wear","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"nightMarketCurtain","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"material":["vinyl-curtain"],"affect":["humid","nocturnal","intimate"]},"parameters":[{"id":"strips","label":"Strips","kind":"number","min":4,"max":24,"default":10,"modulatable":true},{"id":"unevenness","label":"Unevenness","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"swayAmt","label":"Sway","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"roadStitch","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"affect":["travelling","meditative","persistent"],"environment":["road"]},"parameters":[{"id":"lanes","label":"Lanes","kind":"int","min":1,"max":5,"default":2,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":3,"default":1.2,"modulatable":true},{"id":"breakup","label":"Breakup","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"flyoverBeams","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"environment":["urban"],"affect":["infrastructural","heavy","cinematic"]},"parameters":[{"id":"spacing","label":"Spacing","kind":"number","min":0.1,"max":1,"default":0.35,"modulatable":true},{"id":"diagonal","label":"Diagonal","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"scroll","label":"Scroll","kind":"number","min":0,"max":2,"default":0.25,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"fanGuard","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"environment":["domestic"],"affect":["tropical","uncanny"],"motion":["rotate"]},"parameters":[{"id":"spokes","label":"Spokes","kind":"int","min":8,"max":48,"default":20,"modulatable":true},{"id":"offCenter","label":"Off Center","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"spin","label":"Spin","kind":"number","min":0,"max":2,"default":0.3,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"mooringRope","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"environment":["maritime"],"affect":["tactile","slow"]},"parameters":[{"id":"strands","label":"Strands","kind":"int","min":2,"max":6,"default":3,"modulatable":true},{"id":"twist","label":"Twist","kind":"number","min":1,"max":8,"default":3.5,"modulatable":true},{"id":"tension","label":"Tension","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"viaductJoints","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"environment":["urban"],"affect":["brutalist","quiet","metropolitan"]},"parameters":[{"id":"panelScale","label":"Panel Scale","kind":"number","min":1,"max":8,"default":3,"modulatable":true},{"id":"repair","label":"Repair","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"drift","label":"Drift","kind":"number","min":0,"max":0.2,"default":0.05,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"busJacquard","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["taiwan-streetscape"],"affect":["kitsch","nostalgic"],"environment":["transit"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":4,"max":32,"default":14,"modulatable":true},{"id":"switchRate","label":"Switch Rate","kind":"number","min":0.1,"max":2,"default":0.5,"modulatable":true},{"id":"mix","label":"Mix","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"templeZigzag","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["sinosphere"],"affect":["festive","ornate","electric"]},"parameters":[{"id":"layers","label":"Layers","kind":"int","min":2,"max":6,"default":4,"modulatable":true},{"id":"teeth","label":"Teeth","kind":"number","min":4,"max":40,"default":16,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":2,"default":0.4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"polymeter","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"affect":["sweet","intricate","uneasy"],"motion":["polyrhythm"]},"parameters":[{"id":"meterA","label":"Meter A","kind":"int","min":2,"max":7,"default":3,"modulatable":true},{"id":"meterB","label":"Meter B","kind":"int","min":2,"max":9,"default":5,"modulatable":true},{"id":"softness","label":"Softness","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"pcbMaze","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"material":["circuit"],"affect":["retro-tech","playful","cerebral"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":4,"max":40,"default":16,"modulatable":true},{"id":"pads","label":"Pads","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"growth","label":"Growth","kind":"number","min":0,"max":2,"default":0.6,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"bellowsHose","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"material":["industrial-hose"],"affect":["industrial","organic","odd"]},"parameters":[{"id":"folds","label":"Folds","kind":"number","min":1,"max":4,"default":2.2,"modulatable":true},{"id":"density","label":"Density","kind":"number","min":8,"max":48,"default":24,"modulatable":true},{"id":"pressure","label":"Pressure","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"cassetteWindow","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"material":["cassette"],"affect":["analog","personal","obsolete"]},"parameters":[{"id":"windows","label":"Windows","kind":"int","min":1,"max":4,"default":2,"modulatable":true},{"id":"hubSpin","label":"Hub Spin","kind":"number","min":0,"max":2,"default":0.7,"modulatable":true},{"id":"lines","label":"Lines","kind":"number","min":0,"max":1,"default":0.65,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"seigaiha","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"affect":["calm","traditional"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":16,"default":6,"modulatable":true},{"id":"rings","label":"Rings","kind":"int","min":2,"max":8,"default":4,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.01,"max":0.2,"default":0.06,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"asanoha","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"affect":["geometric","traditional"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":16,"default":6,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.004,"max":0.05,"default":0.012,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"kumiko","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"material":["wood-lattice"],"affect":["delicate"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":20,"default":8,"modulatable":true},{"id":"diagonal","label":"Diagonal","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.003,"max":0.04,"default":0.01,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"checker","version":1,"category":"source","costClass":"micro","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"affect":["graphic","traditional"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":40,"default":10,"modulatable":true},{"id":"softness","label":"Softness","kind":"number","min":0,"max":0.5,"default":0.05,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.15,"stateful":false}},{"id":"hexGrid","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"affect":["graphic","traditional"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":24,"default":8,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.004,"max":0.08,"default":0.018,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"contour","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"environment":["terrain"],"affect":["technical","calm"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":0.5,"max":6,"default":2,"modulatable":true},{"id":"levels","label":"Levels","kind":"int","min":3,"max":20,"default":9,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.01,"max":0.2,"default":0.07,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.6,"stateful":false}},{"id":"sunburst","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"culturalTexture":["manga"],"motion":["radial"],"affect":["dramatic","graphic"]},"parameters":[{"id":"rays","label":"Rays","kind":"int","min":8,"max":64,"default":24,"modulatable":true},{"id":"duty","label":"Duty","kind":"number","min":0.05,"max":0.9,"default":0.4,"modulatable":true},{"id":"wobble","label":"Wobble","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"spiral","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"motion":["rotate"],"affect":["hypnotic","graphic"]},"parameters":[{"id":"arms","label":"Arms","kind":"int","min":1,"max":6,"default":2,"modulatable":true},{"id":"pitch","label":"Pitch","kind":"number","min":0.05,"max":1,"default":0.22,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.01,"max":0.3,"default":0.05,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"windows","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"environment":["urban-night"],"affect":["nocturnal","metropolitan"]},"parameters":[{"id":"cols","label":"Columns","kind":"number","min":4,"max":40,"default":14,"modulatable":true},{"id":"litRatio","label":"Lit Ratio","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"glow","label":"Glow","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"chainlink","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","tags":{"material":["galvanized-wire"],"environment":["urban"],"affect":["provisional","restrained"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":4,"max":32,"default":12,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.004,"max":0.06,"default":0.014,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"barcode","version":1,"category":"source","costClass":"micro","impl":"inline","output":"field","tags":{"material":["print"],"affect":["graphic","mundane"]},"parameters":[{"id":"bars","label":"Bars","kind":"number","min":16,"max":128,"default":34,"modulatable":true},{"id":"density","label":"Density","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"petals","version":1,"category":"source","costClass":"micro","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"motion":["breathe"],"affect":["soft","ornate"]},"parameters":[{"id":"count","label":"Count","kind":"int","min":3,"max":16,"default":6,"modulatable":true},{"id":"size","label":"Size","kind":"number","min":0.2,"max":1,"default":0.62,"modulatable":true},{"id":"softness","label":"Softness","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"uroko","version":1,"category":"source","costClass":"medium","impl":"inline","output":"field","tags":{"culturalTexture":["japan"],"affect":["traditional","tactile"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":2,"max":24,"default":8,"modulatable":true},{"id":"overlap","label":"Overlap","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.55,"stateful":false}},{"id":"sdfTunnel","version":1,"category":"source","costClass":"heavy","impl":"inline","output":"field","tags":{"environment":["urban"],"material":["concrete"],"motion":["flythrough"],"affect":["subterranean","propulsive","infrastructural","cinematic"]},"parameters":[{"id":"bore","label":"Bore","kind":"number","min":0.35,"max":1.1,"default":0.6,"modulatable":true},{"id":"pitch","label":"Rib Pitch","kind":"number","min":0.35,"max":1.6,"default":0.8,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":2,"default":0.85,"modulatable":true}],"cost":{"passes":0,"relativeFill":1,"stateful":false}},{"id":"sdfLattice","version":1,"category":"source","costClass":"heavy","impl":"inline","output":"field","tags":{"environment":["urban"],"material":["steel","galvanized"],"motion":["drift"],"affect":["infrastructural","heavy","dense","industrial"]},"parameters":[{"id":"cell","label":"Cell","kind":"number","min":0.35,"max":1.3,"default":0.72,"modulatable":true},{"id":"thickness","label":"Thickness","kind":"number","min":0.02,"max":0.12,"default":0.05,"modulatable":true},{"id":"brace","label":"Brace","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":2,"default":0.7,"modulatable":true}],"cost":{"passes":0,"relativeFill":1.1,"stateful":false}},{"id":"sdfBlob","version":1,"category":"source","costClass":"heavy","impl":"inline","output":"field","tags":{"environment":["club"],"material":["mercury","speaker"],"motion":["pulse"],"affect":["physical","organic","liquid"]},"parameters":[{"id":"blobs","label":"Blobs","kind":"int","min":2,"max":6,"default":4,"modulatable":true},{"id":"radius","label":"Radius","kind":"number","min":0.12,"max":0.45,"default":0.26,"modulatable":true},{"id":"fuse","label":"Fuse","kind":"number","min":0.05,"max":0.4,"default":0.18,"modulatable":true},{"id":"pulse","label":"Pulse","kind":"number","min":0,"max":1,"default":0.6,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.95,"stateful":false}},{"id":"sdfCube","version":1,"category":"source","costClass":"heavy","impl":"inline","output":"field","tags":{"material":["metal","plastic"],"motion":["tumble","spin"],"affect":["graphic","bold","physical"]},"parameters":[{"id":"style","label":"Style","kind":"enum","options":["solid","chamfer","frame"],"default":"solid","modulatable":false},{"id":"count","label":"Count","kind":"int","min":1,"max":4,"default":1,"modulatable":true},{"id":"spin","label":"Spin","kind":"number","min":0,"max":2,"default":0.65,"modulatable":true},{"id":"size","label":"Size","kind":"number","min":0.25,"max":0.8,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.9,"stateful":false}},{"id":"stamp","version":1,"category":"source","costClass":"light","impl":"inline","output":"field","textures":["image"],"tags":{"material":["photographic","print"],"culturalTexture":["signage","logo"],"affect":["literal"]},"parameters":[{"id":"fit","label":"Fit","kind":"enum","options":["contain","cover","tile"],"default":"contain","modulatable":false},{"id":"scale","label":"Scale","kind":"number","min":0.2,"max":4,"default":1,"modulatable":true},{"id":"invert","label":"Invert","kind":"bool","default":false,"modulatable":false}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"noise","version":1,"category":"field","costClass":"medium","impl":"inline","output":"vector","tags":{"material":["organic","noise"],"motion":["turbulent"],"affect":["chaotic"]},"parameters":[{"id":"scale","label":"Scale","kind":"number","min":0.1,"max":8,"default":2,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.15,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.8,"stateful":false}},{"id":"vortex","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"material":["fluid"],"motion":["swirl","rotational"],"affect":["hypnotic"]},"parameters":[{"id":"strength","label":"Strength","kind":"number","min":0,"max":2,"default":1,"modulatable":true},{"id":"falloff","label":"Falloff","kind":"number","min":0.1,"max":4,"default":1.5,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"flow","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"material":["fluid","stream"],"motion":["directional","drift"],"affect":["current"]},"parameters":[{"id":"angle","label":"Angle","kind":"number","min":0,"max":360,"default":45,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":2,"default":0.8,"modulatable":true},{"id":"scale","label":"Scale","kind":"number","min":0.1,"max":8,"default":2,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"ripple","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"motion":["wave","ripple"],"material":["fluid"],"affect":["liquid"]},"parameters":[{"id":"freq","label":"Freq","kind":"number","min":1,"max":30,"default":8,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":3,"default":1,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.15,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"sway","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"motion":["sway"],"affect":["humid"],"material":["vinyl-curtain"]},"parameters":[{"id":"freq","label":"Freq","kind":"number","min":0.5,"max":8,"default":2,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":3,"default":1,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"pulse","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"motion":["pulse","breath"],"affect":["alive"]},"parameters":[{"id":"rate","label":"Rate","kind":"number","min":0.1,"max":4,"default":1,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.15,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.15,"stateful":false}},{"id":"typhoonShear","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"affect":["ominous","tropical","tense"]},"parameters":[{"id":"strength","label":"Strength","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"gustRate","label":"Gust Rate","kind":"number","min":0.1,"max":2,"default":0.4,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"tapeWow","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"material":["tape"],"affect":["analog","tender","unstable"]},"parameters":[{"id":"wow","label":"Wow","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"flutter","label":"Flutter","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"coneField","version":1,"category":"field","costClass":"medium","impl":"inline","output":"vector","tags":{"environment":["club"],"material":["speaker"],"affect":["physical","dense"]},"parameters":[{"id":"cones","label":"Cones","kind":"int","min":1,"max":5,"default":3,"modulatable":true},{"id":"size","label":"Size","kind":"number","min":0.1,"max":0.6,"default":0.3,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.45,"stateful":false}},{"id":"humidityLens","version":1,"category":"field","costClass":"medium","impl":"inline","output":"vector","tags":{"affect":["humid","dreamy","nocturnal"]},"parameters":[{"id":"blobs","label":"Blobs","kind":"number","min":1,"max":6,"default":3,"modulatable":true},{"id":"refraction","label":"Refraction","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.5,"stateful":false}},{"id":"tunnelDraft","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"affect":["subterranean","propulsive","eerie"]},"parameters":[{"id":"pull","label":"Pull","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"escape","label":"Escape","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"hillClimb","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"affect":["effortful","travelling","hypnotic"]},"parameters":[{"id":"gears","label":"Gears","kind":"int","min":2,"max":6,"default":4,"modulatable":true},{"id":"meander","label":"Meander","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"harborBackwash","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"environment":["maritime"],"affect":["suspended","melancholic"]},"parameters":[{"id":"period","label":"Period","kind":"number","min":1,"max":8,"default":3.5,"modulatable":true},{"id":"asymmetry","label":"Asymmetry","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"sleeperRail","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"affect":["nocturnal","travelling","lonely"]},"parameters":[{"id":"speed","label":"Speed","kind":"number","min":0,"max":2,"default":0.8,"modulatable":true},{"id":"swayLong","label":"Sway Long","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"scooterSlipstream","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"culturalTexture":["taiwan-streetscape"],"affect":["kinetic","humid"]},"parameters":[{"id":"riders","label":"Riders","kind":"int","min":1,"max":5,"default":3,"modulatable":true},{"id":"pull","label":"Pull","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"crossingParallax","version":1,"category":"field","costClass":"light","impl":"inline","output":"vector","tags":{"environment":["urban"],"affect":["metropolitan","layered","restless"]},"parameters":[{"id":"layers","label":"Layers","kind":"int","min":2,"max":5,"default":3,"modulatable":true},{"id":"speed","label":"Speed","kind":"number","min":0,"max":2,"default":0.8,"modulatable":true},{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"mirror","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"vector","tags":{"material":["geometric"],"environment":["kaleidoscope"],"affect":["symmetrical"]},"parameters":[{"id":"axis","label":"Axis","kind":"enum","options":["x","y","xy"],"default":"x","modulatable":false}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"repeat","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"vector","tags":{"material":["geometric","tiling"],"environment":["patterned"],"affect":["repetitive","structured"]},"parameters":[{"id":"count","label":"Count","kind":"number","min":1,"max":16,"default":3,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"pixelate","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"vector","tags":{"material":["pixel","digital"],"culturalTexture":["lo-fi","retro"],"affect":["blocky","nostalgic"]},"parameters":[{"id":"size","label":"Size","kind":"number","min":0.002,"max":0.2,"default":0.03,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"threshold","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"field","tags":{"material":["hard-edge","print"],"affect":["graphic","binary"]},"parameters":[{"id":"level","label":"Level","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"softness","label":"Softness","kind":"number","min":0,"max":0.5,"default":0.05,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"dropout","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"field","tags":{"material":["glitch","sparse"],"motion":["flicker"],"affect":["broken","digital"]},"parameters":[{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.25,"modulatable":true},{"id":"scale","label":"Scale","kind":"number","min":1,"max":64,"default":16,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.15,"stateful":false}},{"id":"kaleido","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"vector","tags":{"material":["geometric"],"environment":["kaleidoscope"],"affect":["symmetrical"]},"parameters":[{"id":"segments","label":"Segments","kind":"int","min":2,"max":16,"default":6,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"slice","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"vector","tags":{"material":["compression-noise"],"motion":["glitch"],"affect":["eerie"]},"parameters":[{"id":"bands","label":"Bands","kind":"int","min":2,"max":32,"default":8,"modulatable":true},{"id":"shift","label":"Shift","kind":"number","min":0,"max":0.5,"default":0.12,"modulatable":true},{"id":"rate","label":"Rate","kind":"number","min":0.5,"max":8,"default":2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.15,"stateful":false}},{"id":"posterize","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"field","tags":{"material":["print","poster"],"affect":["graphic"]},"parameters":[{"id":"levels","label":"Levels","kind":"int","min":2,"max":8,"default":4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"invert","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"field","tags":{"material":["negative"],"affect":["inverted"]},"parameters":[{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"macroblock","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"vector","tags":{"material":["web-video"],"affect":["degraded","energetic"]},"parameters":[{"id":"blockSize","label":"Block Size","kind":"number","min":0.02,"max":0.3,"default":0.1,"modulatable":true},{"id":"keyRate","label":"Key Rate","kind":"number","min":0.1,"max":2,"default":0.6,"modulatable":true},{"id":"mix","label":"Mix","kind":"number","min":0,"max":1,"default":0.75,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"corruptSave","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"vector","tags":{"affect":["game-like","eerie","playful"]},"parameters":[{"id":"cellScale","label":"Cell Scale","kind":"number","min":4,"max":40,"default":16,"modulatable":true},{"id":"corruption","label":"Corruption","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"cycle","label":"Cycle","kind":"number","min":2,"max":30,"default":10,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"beatMoire","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"field","tags":{"affect":["optical","psychedelic","precise"]},"parameters":[{"id":"freq","label":"Freq","kind":"number","min":4,"max":80,"default":28,"modulatable":true},{"id":"angleDelta","label":"Angle Delta","kind":"number","min":0,"max":30,"default":8,"modulatable":true},{"id":"mix","label":"Mix","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"scanSlip","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"vector","tags":{"material":["broadcast"],"affect":["nervous","retro"]},"parameters":[{"id":"bandH","label":"Band H","kind":"number","min":0.01,"max":0.2,"default":0.05,"modulatable":true},{"id":"slip","label":"Slip","kind":"number","min":0,"max":0.5,"default":0.18,"modulatable":true},{"id":"travelRate","label":"Travel Rate","kind":"number","min":0.2,"max":4,"default":1.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"polar","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"vector","tags":{"material":["geometric"],"affect":["psychedelic"]},"parameters":[{"id":"twist","label":"Twist","kind":"number","min":0,"max":2,"default":0.5,"modulatable":true},{"id":"zoom","label":"Zoom","kind":"number","min":0.2,"max":4,"default":1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"spin","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"vector","tags":{"material":["geometric"],"affect":["hypnotic","kinetic"]},"parameters":[{"id":"rate","label":"Rate","kind":"number","min":-2,"max":2,"default":0.4,"modulatable":true},{"id":"wobble","label":"Wobble","kind":"number","min":0,"max":1,"default":0.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"xerox","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"field","tags":{"affect":["zine","raw","underground"]},"parameters":[{"id":"generations","label":"Generations","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"cycle","label":"Cycle","kind":"number","min":4,"max":40,"default":12,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"scalerRinging","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"field","tags":{"material":["consumer-tech"],"affect":["harsh","nostalgic"]},"parameters":[{"id":"rings","label":"Rings","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"harshness","label":"Harshness","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"interlaceComb","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"vector","tags":{"affect":["archival","technical","abrasive"]},"parameters":[{"id":"lineH","label":"Line H","kind":"number","min":0.002,"max":0.02,"default":0.008,"modulatable":true},{"id":"comb","label":"Comb","kind":"number","min":0,"max":0.5,"default":0.18,"modulatable":true},{"id":"rate","label":"Rate","kind":"number","min":0.5,"max":8,"default":2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"halftone","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"field","tags":{"material":["print"],"affect":["graphic","nostalgic"]},"parameters":[{"id":"cellScale","label":"Cell Scale","kind":"number","min":20,"max":160,"default":48,"modulatable":true},{"id":"angle","label":"Angle","kind":"number","min":0,"max":90,"default":22,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"outline","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"field","tags":{"material":["hard-edge","print"],"affect":["graphic"]},"parameters":[{"id":"level","label":"Level","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"width","label":"Width","kind":"number","min":0.01,"max":0.3,"default":0.08,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"gate","version":1,"category":"modifier","costClass":"light","impl":"inline","output":"field","tags":{"motion":["flicker"],"affect":["rhythmic","abrasive"]},"parameters":[{"id":"rate","label":"Rate","kind":"number","min":0.5,"max":8,"default":2,"modulatable":true},{"id":"duty","label":"Duty","kind":"number","min":0,"max":1,"default":0.65,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.15,"stateful":false}},{"id":"gamma","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"field","tags":{"affect":["graphic"]},"parameters":[{"id":"curve","label":"Curve","kind":"number","min":0.2,"max":5,"default":0.8,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.05,"stateful":false}},{"id":"grain","version":1,"category":"modifier","costClass":"micro","impl":"inline","output":"field","tags":{"material":["film"],"motion":["flicker"],"affect":["nostalgic","tactile"]},"parameters":[{"id":"amount","label":"Amount","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true},{"id":"size","label":"Size","kind":"number","min":1,"max":8,"default":2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.12,"stateful":false}},{"id":"neon","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["neon","emissive"],"culturalTexture":["cyber"],"affect":["electric"]},"parameters":[{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":200,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.2,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"ink","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["ink","sumi","wash"],"culturalTexture":["calligraphic","east-asian"],"affect":["meditative","organic"]},"parameters":[{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":220,"modulatable":true},{"id":"density","label":"Density","kind":"number","min":0,"max":2,"default":1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"crt","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["crt","phosphor"],"culturalTexture":["retro","broadcast"],"motion":["scan"],"affect":["nostalgic","electric"]},"parameters":[{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":120,"modulatable":true},{"id":"scanline","label":"Scanline","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"aberration","label":"Aberration","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"cheapLed","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["cheap-led"],"culturalTexture":["stadium","signage"],"motion":["flicker"],"affect":["nostalgic","digital"]},"parameters":[{"id":"pitch","label":"Pitch","kind":"number","min":8,"max":128,"default":32,"modulatable":true},{"id":"dropout","label":"Dropout","kind":"number","min":0,"max":1,"default":0.08,"modulatable":true},{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":15,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"fluorescent","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["fluorescent"],"motion":["flicker"],"environment":["interior"],"affect":["nostalgic"]},"parameters":[{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":95,"modulatable":true},{"id":"flicker","label":"Flicker","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"wetConcrete","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["wet-concrete"],"affect":["humid","eerie"]},"parameters":[{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":210,"modulatable":true},{"id":"speckle","label":"Speckle","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"sheen","label":"Sheen","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"misprint","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["print-misregistration"],"affect":["nostalgic"]},"parameters":[{"id":"hue","label":"Hue","kind":"number","min":0,"max":360,"default":0,"modulatable":true},{"id":"fringe","label":"Fringe","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"sodium","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"environment":["urban-night"],"material":["sodium-vapor"],"affect":["nostalgic"]},"parameters":[{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.1,"modulatable":true},{"id":"haze","label":"Haze","kind":"number","min":0,"max":1,"default":0.3,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.2,"stateful":false}},{"id":"brakeLightRain","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"environment":["urban-night"],"affect":["nocturnal","wet"],"culturalTexture":["taiwan-streetscape"]},"parameters":[{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.2,"modulatable":true},{"id":"streak","label":"Streak","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"wetness","label":"Wetness","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"freezerCyan","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"environment":["late-night-store"],"affect":["mundane","sterile"]},"parameters":[{"id":"frost","label":"Frost","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"hum","label":"Hum","kind":"number","min":0,"max":1,"default":0.3,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"minidvFade","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["minidv"],"affect":["2000s","personal","faded"]},"parameters":[{"id":"age","label":"Age","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"chromaNoise","label":"Chroma Noise","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true},{"id":"awbDrift","label":"AWB Drift","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"busPolarization","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"environment":["transit"],"affect":["iridescent","wistful"]},"parameters":[{"id":"bands","label":"Bands","kind":"number","min":0.5,"max":4,"default":1.8,"modulatable":true},{"id":"drift","label":"Drift","kind":"number","min":0,"max":2,"default":0.6,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"asphaltIridescence","version":1,"category":"material","costClass":"medium","impl":"inline","output":"color","tags":{"environment":["urban"],"affect":["wet","accidental"]},"parameters":[{"id":"patches","label":"Patches","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"shift","label":"Shift","kind":"number","min":0,"max":2,"default":0.7,"modulatable":true},{"id":"grit","label":"Grit","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}},{"id":"paCarpet","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["speaker-carpet"],"environment":["backstage"],"affect":["tactile","understated"]},"parameters":[{"id":"fiber","label":"Fiber","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"wear","label":"Wear","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"dust","label":"Dust","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"humidGalvanized","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["galvanized-steel"],"affect":["industrial","humid","cold"]},"parameters":[{"id":"spangle","label":"Spangle","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"film","label":"Film","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"bathroomGlaze","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"culturalTexture":["taiwan-streetscape"],"environment":["domestic"],"affect":["retro","humid"]},"parameters":[{"id":"tint","label":"Tint","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"gloss","label":"Gloss","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"scum","label":"Scum","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"projectorBlackLift","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"environment":["venue"],"affect":["hazy","imperfect"]},"parameters":[{"id":"lift","label":"Lift","kind":"number","min":0,"max":1,"default":0.45,"modulatable":true},{"id":"leak","label":"Leak","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true},{"id":"flutter","label":"Flutter","kind":"number","min":0,"max":1,"default":0.3,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"nicotineCeiling","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"environment":["club"],"affect":["aged","murky"]},"parameters":[{"id":"stain","label":"Stain","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"grain","label":"Grain","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"karaokeLcd","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"culturalTexture":["east-asia-karaoke"],"affect":["cheap","festive","2000s"]},"parameters":[{"id":"angleDrift","label":"Angle Drift","kind":"number","min":0,"max":2,"default":0.7,"modulatable":true},{"id":"cheapness","label":"Cheapness","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.1,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"cdDiffraction","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["compact-disc"],"affect":["shiny","2000s","synthetic"]},"parameters":[{"id":"spectrum","label":"Spectrum","kind":"number","min":0,"max":1,"default":0.65,"modulatable":true},{"id":"lightSpeed","label":"Light Speed","kind":"number","min":0,"max":3,"default":1,"modulatable":true},{"id":"intensity","label":"Intensity","kind":"number","min":0,"max":2,"default":1.15,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"preSilenceBlack","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"affect":["suspended","intimate","final"]},"parameters":[{"id":"descent","label":"Descent","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"residue","label":"Residue","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.25,"stateful":false}},{"id":"seaSalt","version":1,"category":"material","costClass":"medium","impl":"inline","output":"color","tags":{"material":["salt-crust"],"environment":["coastal"],"affect":["weathered","quiet"]},"parameters":[{"id":"growth","label":"Growth","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"crust","label":"Crust","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.6,"stateful":false}},{"id":"sunbleachedTarp","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["tarp"],"environment":["urban"],"affect":["provisional","weathered","local"]},"parameters":[{"id":"fade","label":"Fade","kind":"number","min":0,"max":1,"default":0.55,"modulatable":true},{"id":"creases","label":"Creases","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"weave","label":"Weave","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.45,"stateful":false}},{"id":"riso","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["risograph"],"affect":["zine","playful"]},"parameters":[{"id":"inkA","label":"Ink A Hue","kind":"number","min":0,"max":360,"default":330,"modulatable":true},{"id":"inkB","label":"Ink B Hue","kind":"number","min":0,"max":360,"default":205,"modulatable":true},{"id":"misalign","label":"Misalign","kind":"number","min":0,"max":1,"default":0.35,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.35,"stateful":false}},{"id":"blueprint","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["blueprint"],"affect":["technical","nostalgic"]},"parameters":[{"id":"depth","label":"Depth","kind":"number","min":0,"max":1,"default":0.6,"modulatable":true},{"id":"bleed","label":"Bleed","kind":"number","min":0,"max":1,"default":0.4,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.3,"stateful":false}},{"id":"goldfoil","version":1,"category":"material","costClass":"light","impl":"inline","output":"color","tags":{"material":["gold-leaf"],"culturalTexture":["east-asia"],"affect":["ornate","festive"]},"parameters":[{"id":"sparkle","label":"Sparkle","kind":"number","min":0,"max":1,"default":0.5,"modulatable":true},{"id":"patina","label":"Patina","kind":"number","min":0,"max":1,"default":0.3,"modulatable":true}],"cost":{"passes":0,"relativeFill":0.4,"stateful":false}}])SC_CATALOG";
inline constexpr GeneratedGeneratorDefinition kGeneratorDefinitions[] = {
    {"grid", 1, "source", "light", 0, 0.3, false},
    {"points", 1, "source", "light", 0, 0.45, false},
    {"branch", 1, "source", "medium", 0, 0.7, false},
    {"cells", 1, "source", "medium", 0, 0.75, false},
    {"tiles", 1, "source", "light", 0, 0.35, false},
    {"wires", 1, "source", "light", 0, 0.4, false},
    {"concentric", 1, "source", "light", 0, 0.45, false},
    {"grille", 1, "source", "medium", 0, 0.65, false},
    {"stripes", 1, "source", "light", 0, 0.25, false},
    {"qilouShutter", 1, "source", "medium", 0, 0.55, false},
    {"nightMarketCurtain", 1, "source", "light", 0, 0.4, false},
    {"roadStitch", 1, "source", "light", 0, 0.4, false},
    {"flyoverBeams", 1, "source", "medium", 0, 0.5, false},
    {"fanGuard", 1, "source", "medium", 0, 0.55, false},
    {"mooringRope", 1, "source", "medium", 0, 0.5, false},
    {"viaductJoints", 1, "source", "light", 0, 0.4, false},
    {"busJacquard", 1, "source", "medium", 0, 0.55, false},
    {"templeZigzag", 1, "source", "medium", 0, 0.5, false},
    {"polymeter", 1, "source", "medium", 0, 0.5, false},
    {"pcbMaze", 1, "source", "medium", 0, 0.55, false},
    {"bellowsHose", 1, "source", "medium", 0, 0.55, false},
    {"cassetteWindow", 1, "source", "medium", 0, 0.5, false},
    {"seigaiha", 1, "source", "medium", 0, 0.55, false},
    {"asanoha", 1, "source", "medium", 0, 0.5, false},
    {"kumiko", 1, "source", "light", 0, 0.4, false},
    {"checker", 1, "source", "micro", 0, 0.15, false},
    {"hexGrid", 1, "source", "light", 0, 0.35, false},
    {"contour", 1, "source", "medium", 0, 0.6, false},
    {"sunburst", 1, "source", "light", 0, 0.4, false},
    {"spiral", 1, "source", "light", 0, 0.4, false},
    {"windows", 1, "source", "light", 0, 0.4, false},
    {"chainlink", 1, "source", "light", 0, 0.4, false},
    {"barcode", 1, "source", "micro", 0, 0.25, false},
    {"petals", 1, "source", "micro", 0, 0.3, false},
    {"uroko", 1, "source", "medium", 0, 0.55, false},
    {"sdfTunnel", 1, "source", "heavy", 0, 1, false},
    {"sdfLattice", 1, "source", "heavy", 0, 1.1, false},
    {"sdfBlob", 1, "source", "heavy", 0, 0.95, false},
    {"sdfCube", 1, "source", "heavy", 0, 0.9, false},
    {"stamp", 1, "source", "light", 0, 0.3, false},
    {"noise", 1, "field", "medium", 0, 0.8, false},
    {"vortex", 1, "field", "light", 0, 0.25, false},
    {"flow", 1, "field", "light", 0, 0.4, false},
    {"ripple", 1, "field", "light", 0, 0.3, false},
    {"sway", 1, "field", "light", 0, 0.2, false},
    {"pulse", 1, "field", "light", 0, 0.15, false},
    {"typhoonShear", 1, "field", "light", 0, 0.3, false},
    {"tapeWow", 1, "field", "light", 0, 0.25, false},
    {"coneField", 1, "field", "medium", 0, 0.45, false},
    {"humidityLens", 1, "field", "medium", 0, 0.5, false},
    {"tunnelDraft", 1, "field", "light", 0, 0.3, false},
    {"hillClimb", 1, "field", "light", 0, 0.25, false},
    {"harborBackwash", 1, "field", "light", 0, 0.3, false},
    {"sleeperRail", 1, "field", "light", 0, 0.25, false},
    {"scooterSlipstream", 1, "field", "light", 0, 0.3, false},
    {"crossingParallax", 1, "field", "light", 0, 0.3, false},
    {"mirror", 1, "modifier", "micro", 0, 0.05, false},
    {"repeat", 1, "modifier", "micro", 0, 0.05, false},
    {"pixelate", 1, "modifier", "micro", 0, 0.05, false},
    {"threshold", 1, "modifier", "micro", 0, 0.05, false},
    {"dropout", 1, "modifier", "light", 0, 0.15, false},
    {"kaleido", 1, "modifier", "micro", 0, 0.05, false},
    {"slice", 1, "modifier", "light", 0, 0.15, false},
    {"posterize", 1, "modifier", "micro", 0, 0.05, false},
    {"invert", 1, "modifier", "micro", 0, 0.05, false},
    {"macroblock", 1, "modifier", "light", 0, 0.2, false},
    {"corruptSave", 1, "modifier", "light", 0, 0.25, false},
    {"beatMoire", 1, "modifier", "light", 0, 0.25, false},
    {"scanSlip", 1, "modifier", "light", 0, 0.2, false},
    {"polar", 1, "modifier", "micro", 0, 0.05, false},
    {"spin", 1, "modifier", "micro", 0, 0.05, false},
    {"xerox", 1, "modifier", "light", 0, 0.25, false},
    {"scalerRinging", 1, "modifier", "light", 0, 0.2, false},
    {"interlaceComb", 1, "modifier", "light", 0, 0.2, false},
    {"halftone", 1, "modifier", "light", 0, 0.25, false},
    {"outline", 1, "modifier", "micro", 0, 0.05, false},
    {"gate", 1, "modifier", "light", 0, 0.15, false},
    {"gamma", 1, "modifier", "micro", 0, 0.05, false},
    {"grain", 1, "modifier", "micro", 0, 0.12, false},
    {"neon", 1, "material", "light", 0, 0.2, false},
    {"ink", 1, "material", "light", 0, 0.25, false},
    {"crt", 1, "material", "light", 0, 0.35, false},
    {"cheapLed", 1, "material", "light", 0, 0.4, false},
    {"fluorescent", 1, "material", "light", 0, 0.25, false},
    {"wetConcrete", 1, "material", "light", 0, 0.35, false},
    {"misprint", 1, "material", "light", 0, 0.3, false},
    {"sodium", 1, "material", "light", 0, 0.2, false},
    {"brakeLightRain", 1, "material", "light", 0, 0.35, false},
    {"freezerCyan", 1, "material", "light", 0, 0.3, false},
    {"minidvFade", 1, "material", "light", 0, 0.3, false},
    {"busPolarization", 1, "material", "light", 0, 0.3, false},
    {"asphaltIridescence", 1, "material", "medium", 0, 0.4, false},
    {"paCarpet", 1, "material", "light", 0, 0.35, false},
    {"humidGalvanized", 1, "material", "light", 0, 0.35, false},
    {"bathroomGlaze", 1, "material", "light", 0, 0.35, false},
    {"projectorBlackLift", 1, "material", "light", 0, 0.3, false},
    {"nicotineCeiling", 1, "material", "light", 0, 0.3, false},
    {"karaokeLcd", 1, "material", "light", 0, 0.3, false},
    {"cdDiffraction", 1, "material", "light", 0, 0.35, false},
    {"preSilenceBlack", 1, "material", "light", 0, 0.25, false},
    {"seaSalt", 1, "material", "medium", 0, 0.6, false},
    {"sunbleachedTarp", 1, "material", "light", 0, 0.45, false},
    {"riso", 1, "material", "light", 0, 0.35, false},
    {"blueprint", 1, "material", "light", 0, 0.3, false},
    {"goldfoil", 1, "material", "light", 0, 0.4, false},
};
inline constexpr GeneratedParameterDefinition kParameterDefinitions[] = {
    {"grid", "cells", "int", 2, 64, true, true, ""},
    {"grid", "thickness", "number", 0, 1, true, true, ""},
    {"points", "density", "number", 1, 64, true, true, ""},
    {"points", "size", "number", 0.01, 1, true, true, ""},
    {"branch", "depth", "int", 1, 6, true, true, ""},
    {"branch", "angle", "number", 0, 1.5, true, true, ""},
    {"branch", "thickness", "number", 0.001, 0.2, true, true, ""},
    {"cells", "scale", "number", 1, 32, true, true, ""},
    {"cells", "edge", "number", 0, 1, true, true, ""},
    {"tiles", "scale", "number", 2, 40, true, true, ""},
    {"tiles", "gap", "number", 0.01, 0.3, true, true, ""},
    {"tiles", "stagger", "number", 0, 1, true, true, ""},
    {"wires", "count", "int", 1, 8, true, true, ""},
    {"wires", "sag", "number", 0, 1, true, true, ""},
    {"wires", "thickness", "number", 0.002, 0.05, true, true, ""},
    {"concentric", "count", "number", 2, 40, true, true, ""},
    {"concentric", "thickness", "number", 0.005, 0.2, true, true, ""},
    {"concentric", "wobble", "number", 0, 1, true, true, ""},
    {"grille", "folds", "int", 2, 12, true, true, ""},
    {"grille", "density", "int", 1, 8, true, true, ""},
    {"grille", "thickness", "number", 0.004, 0.06, true, true, ""},
    {"stripes", "count", "number", 2, 64, true, true, ""},
    {"stripes", "duty", "number", 0.05, 0.95, true, true, ""},
    {"stripes", "angle", "number", 0, 180, true, true, ""},
    {"qilouShutter", "density", "number", 8, 64, true, true, ""},
    {"qilouShutter", "openness", "number", 0, 1, true, true, ""},
    {"qilouShutter", "wear", "number", 0, 1, true, true, ""},
    {"nightMarketCurtain", "strips", "number", 4, 24, true, true, ""},
    {"nightMarketCurtain", "unevenness", "number", 0, 1, true, true, ""},
    {"nightMarketCurtain", "swayAmt", "number", 0, 1, true, true, ""},
    {"roadStitch", "lanes", "int", 1, 5, true, true, ""},
    {"roadStitch", "speed", "number", 0, 3, true, true, ""},
    {"roadStitch", "breakup", "number", 0, 1, true, true, ""},
    {"flyoverBeams", "spacing", "number", 0.1, 1, true, true, ""},
    {"flyoverBeams", "diagonal", "number", 0, 1, true, true, ""},
    {"flyoverBeams", "scroll", "number", 0, 2, true, true, ""},
    {"fanGuard", "spokes", "int", 8, 48, true, true, ""},
    {"fanGuard", "offCenter", "number", 0, 1, true, true, ""},
    {"fanGuard", "spin", "number", 0, 2, true, true, ""},
    {"mooringRope", "strands", "int", 2, 6, true, true, ""},
    {"mooringRope", "twist", "number", 1, 8, true, true, ""},
    {"mooringRope", "tension", "number", 0, 1, true, true, ""},
    {"viaductJoints", "panelScale", "number", 1, 8, true, true, ""},
    {"viaductJoints", "repair", "number", 0, 1, true, true, ""},
    {"viaductJoints", "drift", "number", 0, 0.2, true, true, ""},
    {"busJacquard", "scale", "number", 4, 32, true, true, ""},
    {"busJacquard", "switchRate", "number", 0.1, 2, true, true, ""},
    {"busJacquard", "mix", "number", 0, 1, true, true, ""},
    {"templeZigzag", "layers", "int", 2, 6, true, true, ""},
    {"templeZigzag", "teeth", "number", 4, 40, true, true, ""},
    {"templeZigzag", "speed", "number", 0, 2, true, true, ""},
    {"polymeter", "meterA", "int", 2, 7, true, true, ""},
    {"polymeter", "meterB", "int", 2, 9, true, true, ""},
    {"polymeter", "softness", "number", 0, 1, true, true, ""},
    {"pcbMaze", "scale", "number", 4, 40, true, true, ""},
    {"pcbMaze", "pads", "number", 0, 1, true, true, ""},
    {"pcbMaze", "growth", "number", 0, 2, true, true, ""},
    {"bellowsHose", "folds", "number", 1, 4, true, true, ""},
    {"bellowsHose", "density", "number", 8, 48, true, true, ""},
    {"bellowsHose", "pressure", "number", 0, 1, true, true, ""},
    {"cassetteWindow", "windows", "int", 1, 4, true, true, ""},
    {"cassetteWindow", "hubSpin", "number", 0, 2, true, true, ""},
    {"cassetteWindow", "lines", "number", 0, 1, true, true, ""},
    {"seigaiha", "scale", "number", 2, 16, true, true, ""},
    {"seigaiha", "rings", "int", 2, 8, true, true, ""},
    {"seigaiha", "thickness", "number", 0.01, 0.2, true, true, ""},
    {"asanoha", "scale", "number", 2, 16, true, true, ""},
    {"asanoha", "thickness", "number", 0.004, 0.05, true, true, ""},
    {"kumiko", "scale", "number", 2, 20, true, true, ""},
    {"kumiko", "diagonal", "number", 0, 1, true, true, ""},
    {"kumiko", "thickness", "number", 0.003, 0.04, true, true, ""},
    {"checker", "scale", "number", 2, 40, true, true, ""},
    {"checker", "softness", "number", 0, 0.5, true, true, ""},
    {"hexGrid", "scale", "number", 2, 24, true, true, ""},
    {"hexGrid", "thickness", "number", 0.004, 0.08, true, true, ""},
    {"contour", "scale", "number", 0.5, 6, true, true, ""},
    {"contour", "levels", "int", 3, 20, true, true, ""},
    {"contour", "thickness", "number", 0.01, 0.2, true, true, ""},
    {"sunburst", "rays", "int", 8, 64, true, true, ""},
    {"sunburst", "duty", "number", 0.05, 0.9, true, true, ""},
    {"sunburst", "wobble", "number", 0, 1, true, true, ""},
    {"spiral", "arms", "int", 1, 6, true, true, ""},
    {"spiral", "pitch", "number", 0.05, 1, true, true, ""},
    {"spiral", "thickness", "number", 0.01, 0.3, true, true, ""},
    {"windows", "cols", "number", 4, 40, true, true, ""},
    {"windows", "litRatio", "number", 0, 1, true, true, ""},
    {"windows", "glow", "number", 0, 1, true, true, ""},
    {"chainlink", "scale", "number", 4, 32, true, true, ""},
    {"chainlink", "thickness", "number", 0.004, 0.06, true, true, ""},
    {"barcode", "bars", "number", 16, 128, true, true, ""},
    {"barcode", "density", "number", 0, 1, true, true, ""},
    {"petals", "count", "int", 3, 16, true, true, ""},
    {"petals", "size", "number", 0.2, 1, true, true, ""},
    {"petals", "softness", "number", 0, 1, true, true, ""},
    {"uroko", "scale", "number", 2, 24, true, true, ""},
    {"uroko", "overlap", "number", 0, 1, true, true, ""},
    {"sdfTunnel", "bore", "number", 0.35, 1.1, true, true, ""},
    {"sdfTunnel", "pitch", "number", 0.35, 1.6, true, true, ""},
    {"sdfTunnel", "speed", "number", 0, 2, true, true, ""},
    {"sdfLattice", "cell", "number", 0.35, 1.3, true, true, ""},
    {"sdfLattice", "thickness", "number", 0.02, 0.12, true, true, ""},
    {"sdfLattice", "brace", "number", 0, 1, true, true, ""},
    {"sdfLattice", "speed", "number", 0, 2, true, true, ""},
    {"sdfBlob", "blobs", "int", 2, 6, true, true, ""},
    {"sdfBlob", "radius", "number", 0.12, 0.45, true, true, ""},
    {"sdfBlob", "fuse", "number", 0.05, 0.4, true, true, ""},
    {"sdfBlob", "pulse", "number", 0, 1, true, true, ""},
    {"sdfCube", "style", "enum", 0, 0, false, false, "solid|chamfer|frame"},
    {"sdfCube", "count", "int", 1, 4, true, true, ""},
    {"sdfCube", "spin", "number", 0, 2, true, true, ""},
    {"sdfCube", "size", "number", 0.25, 0.8, true, true, ""},
    {"stamp", "fit", "enum", 0, 0, false, false, "contain|cover|tile"},
    {"stamp", "scale", "number", 0.2, 4, true, true, ""},
    {"stamp", "invert", "bool", 0, 0, false, false, ""},
    {"noise", "scale", "number", 0.1, 8, true, true, ""},
    {"noise", "amount", "number", 0, 1, true, true, ""},
    {"vortex", "strength", "number", 0, 2, true, true, ""},
    {"vortex", "falloff", "number", 0.1, 4, true, true, ""},
    {"vortex", "amount", "number", 0, 1, true, true, ""},
    {"flow", "angle", "number", 0, 360, true, true, ""},
    {"flow", "speed", "number", 0, 2, true, true, ""},
    {"flow", "scale", "number", 0.1, 8, true, true, ""},
    {"flow", "amount", "number", 0, 1, true, true, ""},
    {"ripple", "freq", "number", 1, 30, true, true, ""},
    {"ripple", "speed", "number", 0, 3, true, true, ""},
    {"ripple", "amount", "number", 0, 1, true, true, ""},
    {"sway", "freq", "number", 0.5, 8, true, true, ""},
    {"sway", "speed", "number", 0, 3, true, true, ""},
    {"sway", "amount", "number", 0, 1, true, true, ""},
    {"pulse", "rate", "number", 0.1, 4, true, true, ""},
    {"pulse", "amount", "number", 0, 1, true, true, ""},
    {"typhoonShear", "strength", "number", 0, 1, true, true, ""},
    {"typhoonShear", "gustRate", "number", 0.1, 2, true, true, ""},
    {"typhoonShear", "amount", "number", 0, 1, true, true, ""},
    {"tapeWow", "wow", "number", 0, 1, true, true, ""},
    {"tapeWow", "flutter", "number", 0, 1, true, true, ""},
    {"tapeWow", "amount", "number", 0, 1, true, true, ""},
    {"coneField", "cones", "int", 1, 5, true, true, ""},
    {"coneField", "size", "number", 0.1, 0.6, true, true, ""},
    {"coneField", "amount", "number", 0, 1, true, true, ""},
    {"humidityLens", "blobs", "number", 1, 6, true, true, ""},
    {"humidityLens", "refraction", "number", 0, 1, true, true, ""},
    {"humidityLens", "amount", "number", 0, 1, true, true, ""},
    {"tunnelDraft", "pull", "number", 0, 1, true, true, ""},
    {"tunnelDraft", "escape", "number", 0, 1, true, true, ""},
    {"tunnelDraft", "amount", "number", 0, 1, true, true, ""},
    {"hillClimb", "gears", "int", 2, 6, true, true, ""},
    {"hillClimb", "meander", "number", 0, 1, true, true, ""},
    {"hillClimb", "amount", "number", 0, 1, true, true, ""},
    {"harborBackwash", "period", "number", 1, 8, true, true, ""},
    {"harborBackwash", "asymmetry", "number", 0, 1, true, true, ""},
    {"harborBackwash", "amount", "number", 0, 1, true, true, ""},
    {"sleeperRail", "speed", "number", 0, 2, true, true, ""},
    {"sleeperRail", "swayLong", "number", 0, 1, true, true, ""},
    {"sleeperRail", "amount", "number", 0, 1, true, true, ""},
    {"scooterSlipstream", "riders", "int", 1, 5, true, true, ""},
    {"scooterSlipstream", "pull", "number", 0, 1, true, true, ""},
    {"scooterSlipstream", "amount", "number", 0, 1, true, true, ""},
    {"crossingParallax", "layers", "int", 2, 5, true, true, ""},
    {"crossingParallax", "speed", "number", 0, 2, true, true, ""},
    {"crossingParallax", "amount", "number", 0, 1, true, true, ""},
    {"mirror", "axis", "enum", 0, 0, false, false, "x|y|xy"},
    {"repeat", "count", "number", 1, 16, true, true, ""},
    {"pixelate", "size", "number", 0.002, 0.2, true, true, ""},
    {"threshold", "level", "number", 0, 1, true, true, ""},
    {"threshold", "softness", "number", 0, 0.5, true, true, ""},
    {"dropout", "amount", "number", 0, 1, true, true, ""},
    {"dropout", "scale", "number", 1, 64, true, true, ""},
    {"kaleido", "segments", "int", 2, 16, true, true, ""},
    {"slice", "bands", "int", 2, 32, true, true, ""},
    {"slice", "shift", "number", 0, 0.5, true, true, ""},
    {"slice", "rate", "number", 0.5, 8, true, true, ""},
    {"posterize", "levels", "int", 2, 8, true, true, ""},
    {"invert", "amount", "number", 0, 1, true, true, ""},
    {"macroblock", "blockSize", "number", 0.02, 0.3, true, true, ""},
    {"macroblock", "keyRate", "number", 0.1, 2, true, true, ""},
    {"macroblock", "mix", "number", 0, 1, true, true, ""},
    {"corruptSave", "cellScale", "number", 4, 40, true, true, ""},
    {"corruptSave", "corruption", "number", 0, 1, true, true, ""},
    {"corruptSave", "cycle", "number", 2, 30, true, true, ""},
    {"beatMoire", "freq", "number", 4, 80, true, true, ""},
    {"beatMoire", "angleDelta", "number", 0, 30, true, true, ""},
    {"beatMoire", "mix", "number", 0, 1, true, true, ""},
    {"scanSlip", "bandH", "number", 0.01, 0.2, true, true, ""},
    {"scanSlip", "slip", "number", 0, 0.5, true, true, ""},
    {"scanSlip", "travelRate", "number", 0.2, 4, true, true, ""},
    {"polar", "twist", "number", 0, 2, true, true, ""},
    {"polar", "zoom", "number", 0.2, 4, true, true, ""},
    {"spin", "rate", "number", -2, 2, true, true, ""},
    {"spin", "wobble", "number", 0, 1, true, true, ""},
    {"xerox", "generations", "number", 0, 1, true, true, ""},
    {"xerox", "cycle", "number", 4, 40, true, true, ""},
    {"scalerRinging", "rings", "number", 0, 1, true, true, ""},
    {"scalerRinging", "harshness", "number", 0, 1, true, true, ""},
    {"interlaceComb", "lineH", "number", 0.002, 0.02, true, true, ""},
    {"interlaceComb", "comb", "number", 0, 0.5, true, true, ""},
    {"interlaceComb", "rate", "number", 0.5, 8, true, true, ""},
    {"halftone", "cellScale", "number", 20, 160, true, true, ""},
    {"halftone", "angle", "number", 0, 90, true, true, ""},
    {"outline", "level", "number", 0, 1, true, true, ""},
    {"outline", "width", "number", 0.01, 0.3, true, true, ""},
    {"gate", "rate", "number", 0.5, 8, true, true, ""},
    {"gate", "duty", "number", 0, 1, true, true, ""},
    {"gamma", "curve", "number", 0.2, 5, true, true, ""},
    {"grain", "amount", "number", 0, 1, true, true, ""},
    {"grain", "size", "number", 1, 8, true, true, ""},
    {"neon", "hue", "number", 0, 360, true, true, ""},
    {"neon", "intensity", "number", 0, 2, true, true, ""},
    {"ink", "hue", "number", 0, 360, true, true, ""},
    {"ink", "density", "number", 0, 2, true, true, ""},
    {"crt", "hue", "number", 0, 360, true, true, ""},
    {"crt", "scanline", "number", 0, 1, true, true, ""},
    {"crt", "aberration", "number", 0, 1, true, true, ""},
    {"cheapLed", "pitch", "number", 8, 128, true, true, ""},
    {"cheapLed", "dropout", "number", 0, 1, true, true, ""},
    {"cheapLed", "hue", "number", 0, 360, true, true, ""},
    {"fluorescent", "hue", "number", 0, 360, true, true, ""},
    {"fluorescent", "flicker", "number", 0, 1, true, true, ""},
    {"fluorescent", "intensity", "number", 0, 2, true, true, ""},
    {"wetConcrete", "hue", "number", 0, 360, true, true, ""},
    {"wetConcrete", "speckle", "number", 0, 1, true, true, ""},
    {"wetConcrete", "sheen", "number", 0, 1, true, true, ""},
    {"misprint", "hue", "number", 0, 360, true, true, ""},
    {"misprint", "fringe", "number", 0, 1, true, true, ""},
    {"misprint", "intensity", "number", 0, 2, true, true, ""},
    {"sodium", "intensity", "number", 0, 2, true, true, ""},
    {"sodium", "haze", "number", 0, 1, true, true, ""},
    {"brakeLightRain", "intensity", "number", 0, 2, true, true, ""},
    {"brakeLightRain", "streak", "number", 0, 1, true, true, ""},
    {"brakeLightRain", "wetness", "number", 0, 1, true, true, ""},
    {"freezerCyan", "frost", "number", 0, 1, true, true, ""},
    {"freezerCyan", "hum", "number", 0, 1, true, true, ""},
    {"freezerCyan", "intensity", "number", 0, 2, true, true, ""},
    {"minidvFade", "age", "number", 0, 1, true, true, ""},
    {"minidvFade", "chromaNoise", "number", 0, 1, true, true, ""},
    {"minidvFade", "awbDrift", "number", 0, 1, true, true, ""},
    {"busPolarization", "bands", "number", 0.5, 4, true, true, ""},
    {"busPolarization", "drift", "number", 0, 2, true, true, ""},
    {"busPolarization", "intensity", "number", 0, 2, true, true, ""},
    {"asphaltIridescence", "patches", "number", 0, 1, true, true, ""},
    {"asphaltIridescence", "shift", "number", 0, 2, true, true, ""},
    {"asphaltIridescence", "grit", "number", 0, 1, true, true, ""},
    {"paCarpet", "fiber", "number", 0, 1, true, true, ""},
    {"paCarpet", "wear", "number", 0, 1, true, true, ""},
    {"paCarpet", "dust", "number", 0, 1, true, true, ""},
    {"humidGalvanized", "spangle", "number", 0, 1, true, true, ""},
    {"humidGalvanized", "film", "number", 0, 1, true, true, ""},
    {"humidGalvanized", "intensity", "number", 0, 2, true, true, ""},
    {"bathroomGlaze", "tint", "number", 0, 1, true, true, ""},
    {"bathroomGlaze", "gloss", "number", 0, 1, true, true, ""},
    {"bathroomGlaze", "scum", "number", 0, 1, true, true, ""},
    {"projectorBlackLift", "lift", "number", 0, 1, true, true, ""},
    {"projectorBlackLift", "leak", "number", 0, 1, true, true, ""},
    {"projectorBlackLift", "flutter", "number", 0, 1, true, true, ""},
    {"nicotineCeiling", "stain", "number", 0, 1, true, true, ""},
    {"nicotineCeiling", "grain", "number", 0, 1, true, true, ""},
    {"nicotineCeiling", "intensity", "number", 0, 2, true, true, ""},
    {"karaokeLcd", "angleDrift", "number", 0, 2, true, true, ""},
    {"karaokeLcd", "cheapness", "number", 0, 1, true, true, ""},
    {"karaokeLcd", "intensity", "number", 0, 2, true, true, ""},
    {"cdDiffraction", "spectrum", "number", 0, 1, true, true, ""},
    {"cdDiffraction", "lightSpeed", "number", 0, 3, true, true, ""},
    {"cdDiffraction", "intensity", "number", 0, 2, true, true, ""},
    {"preSilenceBlack", "descent", "number", 0, 1, true, true, ""},
    {"preSilenceBlack", "residue", "number", 0, 1, true, true, ""},
    {"seaSalt", "growth", "number", 0, 1, true, true, ""},
    {"seaSalt", "crust", "number", 0, 1, true, true, ""},
    {"sunbleachedTarp", "fade", "number", 0, 1, true, true, ""},
    {"sunbleachedTarp", "creases", "number", 0, 1, true, true, ""},
    {"sunbleachedTarp", "weave", "number", 0, 1, true, true, ""},
    {"riso", "inkA", "number", 0, 360, true, true, ""},
    {"riso", "inkB", "number", 0, 360, true, true, ""},
    {"riso", "misalign", "number", 0, 1, true, true, ""},
    {"blueprint", "depth", "number", 0, 1, true, true, ""},
    {"blueprint", "bleed", "number", 0, 1, true, true, ""},
    {"goldfoil", "sparkle", "number", 0, 1, true, true, ""},
    {"goldfoil", "patina", "number", 0, 1, true, true, ""},
};
inline constexpr GeneratedTextureDefinition kTextureDefinitions[] = {
    {"stamp", "image"},
};
inline constexpr std::size_t kGeneratorDefinitionCount =
    sizeof(kGeneratorDefinitions) / sizeof(kGeneratorDefinitions[0]);
inline constexpr std::size_t kParameterDefinitionCount =
    sizeof(kParameterDefinitions) / sizeof(kParameterDefinitions[0]);
inline constexpr std::size_t kTextureDefinitionCount =
    sizeof(kTextureDefinitions) / sizeof(kTextureDefinitions[0]);
} // namespace stackchan
// clang-format on
